### ISSUE TITLE
Mobile navigation only has hyperlinks for the main headings, not sub-headings

### ISSUE THREAD

**Issue by bobsummerwill** [ETCGrantsDAO/etc-grants-dao-website#8]
The desktop navigation includes hyperlinks for main headings and sub-headings, but the mobile only has the main headings.

**Comment by SPTechnology** [comment]
I have fixed it in latest pull request

**Comment by bobsummerwill** [comment]
Right, but that still needs bringing in as a new PR without merge conflicts.
The hamburger control is still broken there, so I can see the fixes even if apply your unmerged PR changes for this.

**Comment by SPTechnology** [comment]
Fixed in new PR

**Comment by bobsummerwill** [comment]
Confirmed fixed.  Thank you!
